base_url = "https://nsg.cc"
title = "nsg's blog"
compile_sass = true
minify_html = true
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"
paginate_by = 10
default_language = "en"
port = 8080

taxonomies = [
    { name = "tags", feed = true}
]

[markdown]
highlight_code = true
highlight_theme = "zenburn"
