base_url = "https://nsg.cc"
title = "nsg's blog"
compile_sass = true
minify_html = true
build_search_index = true
generate_feeds = true
feed_filenames = ["rss.xml"]
feed_limit = 20
default_language = "en"

taxonomies = [
    { name = "tags", feed = true}
]

[markdown]
highlight_code = true
highlight_theme = "zenburn"
