#!/bin/bash

# Path to the "adb" binary, found in the Android SDK.
PATH_TO_ADB="/home/s/android/android-sdk-linux_x86-1.5_r3/tools/adb"

# Azid log path
LOG_PATH="/var/log/azid.log"

# Path to nohup
NOHUP="/usr/bin/nohup"

# Path to openvpn
OPENVPN="/usr/sbin/openvpn"

# OpenVPN pid-file
OPENVPN_PID="/tmp/azilink.pid"

# DNS service, default or opendns
DNS_TYPE="opendns"

# Azid install path
ROOT_PATH="/opt/azid"

# Start azi deamon (some notifications).
START_AZID="true"
